### ISSUE TITLE
manual/latex: bibtex source file is missing

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#102]
The manual contains only the bibtex compiled file: `stl2018man.bbl`.
It would be great to acquire the original bib-file: `stl2018man.bib`

Otherwise the formatting of the references would need to be done manually.

**Comment by simaocampos** [comment]
As far as I know there were no additional entries after the last editing work by Yusuke for the 2014 prototype (evolving) STL. So the files to look for are ugst.bib as main library, last updated 2013. If I recall correctly, you run bibtex after running latex once, for stl2018man and it will generate the necessary BBL file.

**Comment by dennisguse** [comment]
Your are right.
Perfect.
