### ISSUE TITLE
manual/latex: reference missing - AC-1004-Q10-15

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#110]
The reference `AC-1004-Q10-15` is not defined.
It is referenced in `basop.tex`.

It is about the the dynamic ram counting tool.

@simaocampos Do you recall, which document is actually referenced?

**Comment by simaocampos** [comment]
This is in the IFA for Q10/16 in the 2009-2012 Study Period. 
Source: | France Telecom Orange
Title: | Software tool to compute dynamic RAM
Question(s): | ITU-T Study Group 16, Question 10/16, Study Period 2009-2012
Date: | Geneva, 6 – 9 April 2010
Doc.No. | AC-1004-Q10-15
URL: | https://www.itu.int/ifa/t/2009/sg16/exchange/wp3/q10/1004Geneva/   (Folder)   https://www.itu.int/ifa/t/2009/sg16/exchange/wp3/q10/1004Geneva/AC-1004-Q10-15-dram.doc   (file)

**Comment by simaocampos** [comment]
I suggest to try adding the following in ugst.bib:
@techreport(AC-1004-Q10-15,
title= "{Software tool to compute dynamic RAM}",
author="{France Telecom Orange}",
type= "{Rapporteur Group meeting Contribution}",
number= "AC-1004-Q10-15",
institution= "ITU-T Study Group 16 Q10/16",
year= "2009-2012",
url = "\url{https://www.itu.int/ifa/t/2009/sg16/exchange/wp3/q10/1004Geneva/AC-1004-Q10-15-dram.doc}"
)

But I do not know if all necessary packages are being loaded for bibtex to be able to handle the URL entry. See answer #2 at: https://tex.stackexchange.com/questions/316733/adding-url-to-bibtex

**Comment by dennisguse** [comment]
Thanks. Will update the bibliography in the evening.

**Comment by simaocampos** [comment]
Actually now as bibliography.bib as you renamed it.
Simão
