### ISSUE TITLE
A fresh clone of the repository shows modified files

### ISSUE THREAD

**Issue by ludomal** [openitu/STL#113]
On osx, a fresh checkout of the repository shows modified files, preventing further commits:

	Changes not staged for commit:
	(use "git add <file>..." to update what will be committed)
	(use "git checkout -- <file>..." to discard changes in working directory)

		modified:   manual/LaTeX/graphics/lp14-h0.pdf
		modified:   manual/LaTeX/graphics/lp14.pdf
		modified:   manual/LaTeX/graphics/lp1p5-h0.pdf
		modified:   manual/LaTeX/graphics/lp1p5.pdf
		modified:   manual/LaTeX/graphics/lp20-h0.pdf
		modified:   manual/LaTeX/graphics/lp20.pdf

What is different with these files?

**Comment by dennisguse** [comment]
Same issue here. Will check in the evening.

**Comment by simaocampos** [comment]
Not sure why they show as modified.

The …-h0 files are filter impulse responses, the others …pdf files are the frequency response of the respective filter.

I believe the PDF is used to include the figures in the filter chapter (in my time, I used to embed a PS file, but I believe Yusuke changed that to PDF.



        modified:   manual/LaTeX/graphics/lp14-h0.pdf

        modified:   manual/LaTeX/graphics/lp14.pdf

        modified:   manual/LaTeX/graphics/lp1p5-h0.pdf

        modified:   manual/LaTeX/graphics/lp1p5.pdf

        modified:   manual/LaTeX/graphics/lp20-h0.pdf

        modified:   manual/LaTeX/graphics/lp20.pdf

**Comment by dennisguse** [comment]
This effect does not show up on my Debian (Git 2.11.0) while I could observe it on Windows (using Github for Windows).
Seems to be operating system dependent?

About the files: I extracted these files from the compiled PDF, so compilation of the manual would be working again.

My guess is that the file permissions changed.
@ludomal What does `git diff` report on Windows (I don't have Windows dev-machine at hand before mid next week)?

What I see on Debian (everything as expected):
```
user@noname:~/hack$ git clone https://github.com/openitu/STL STLtest
Cloning into 'STLtest'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 3325 (delta 2), reused 0 (delta 0), pack-reused 3316
Receiving objects: 100% (3325/3325), 69.08 MiB | 484.00 KiB/s, done.
Resolving deltas: 100% (1441/1441), done.
user@noname:~/hack$ cd STLtest/
user@noname:~/hack/STLtest$ git diff
user@noname:~/hack/STLtest$ git status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working tree clean
user@noname:~/hack/STLtest/manual/LaTeX/graphics$ ls -la lp14-h0.pdf
-rw-r--r-- 1 user user 7857 Oct 31 23:04 lp14-h0.pdf
```

**Comment by ludomal** [comment]
On my mac:
```
git diff
diff --git a/manual/LaTeX/graphics/LP14-h0.pdf b/manual/LaTeX/graphics/LP14-h0.pdf
index b3cbdc8..bc78da5 100644
Binary files a/manual/LaTeX/graphics/LP14-h0.pdf and b/manual/LaTeX/graphics/LP14-h0.pdf differ
diff --git a/manual/LaTeX/graphics/LP14.pdf b/manual/LaTeX/graphics/LP14.pdf
index 0dacc2b..d0bdea1 100644
Binary files a/manual/LaTeX/graphics/LP14.pdf and b/manual/LaTeX/graphics/LP14.pdf differ
diff --git a/manual/LaTeX/graphics/LP1p5-h0.pdf b/manual/LaTeX/graphics/LP1p5-h0.pdf
index a9f0068..97292aa 100644
Binary files a/manual/LaTeX/graphics/LP1p5-h0.pdf and b/manual/LaTeX/graphics/LP1p5-h0.pdf differ
diff --git a/manual/LaTeX/graphics/LP1p5.pdf b/manual/LaTeX/graphics/LP1p5.pdf
index 6ef2ed0..8c9ee36 100644
Binary files a/manual/LaTeX/graphics/LP1p5.pdf and b/manual/LaTeX/graphics/LP1p5.pdf differ
diff --git a/manual/LaTeX/graphics/LP20-h0.pdf b/manual/LaTeX/graphics/LP20-h0.pdf
index 42226d3..30770fa 100644
Binary files a/manual/LaTeX/graphics/LP20-h0.pdf and b/manual/LaTeX/graphics/LP20-h0.pdf differ
diff --git a/manual/LaTeX/graphics/LP20.pdf b/manual/LaTeX/graphics/LP20.pdf
index 5c00794..0420ba9 100644
Binary files a/manual/LaTeX/graphics/LP20.pdf and b/manual/LaTeX/graphics/LP20.pdf differ

```

**Comment by ludomal** [comment]
It works fine on Ubuntu, the tree is clean.

**Comment by dennisguse** [comment]
Interestingly, Windows converts the newly added files to lower case.
Git recognizes the change, but _adds_ the lower case files while keeping the original ones.
I tested this on W10 with Github Deskop and the result can be seen here (look for lp20.pdf vs LP20.pdf): https://github.com/openitu/STL/tree/windowsClone/manual/LaTeX/graphics

 Although I saw the same result on W10 (for `diff`), the files are not different after commit and push on my Debian (tested using `diff`).

So, it seems to be the case-sensitivity of the file system (Windows usually isn't and @ludomal MacOS might also not be).
However, I honestly don't know why this only occurred for the 6 files I changed...

One solution would be to make these files lower case.

**Comment by simaocampos** [comment]
That would be a wise approach - all files lowercase - as this is the lowest common denominator.

Simão

**Comment by ludomal** [comment]
The issue seems to be because two versions of these 6 files were pushed with different filename capitalization. When checked out on Linux, both versions of the files are pulled and coexist, however on GitHub, Mac and Windows one file overwrites the other one resulting in modified files.

On Linux:
```
-rw-r--r-- 1 root root   7857 Nov  5 14:40 lp14-h0.pdf
-rw-r--r-- 1 root root  12168 Nov  5 14:40 LP14-h0.pdf
-rw-r--r-- 1 root root  23640 Nov  5 14:40 lp14.pdf
-rw-r--r-- 1 root root  36144 Nov  5 14:40 LP14.pdf
-rw-r--r-- 1 root root   9382 Nov  5 14:40 lp1p5-h0.pdf
-rw-r--r-- 1 root root  14309 Nov  5 14:40 LP1p5-h0.pdf
-rw-r--r-- 1 root root  42788 Nov  5 14:40 lp1p5.pdf
-rw-r--r-- 1 root root  63553 Nov  5 14:40 LP1p5.pdf
-rw-r--r-- 1 root root 679904 Nov  5 14:40 lp20-h0.pdf
-rw-r--r-- 1 root root  14747 Nov  5 14:40 LP20-h0.pdf
-rw-r--r-- 1 root root 793914 Nov  5 14:40 lp20.pdf
-rw-r--r-- 1 root root  24721 Nov  5 14:40 LP20.pdf
````

On Mac:
```
-rw-r--r--    1 root root    7857 Oct 29 15:06 lp14-h0.pdf
-rw-r--r--    1 root root   23640 Oct 29 15:06 lp14.pdf
-rw-r--r--    1 root root    9382 Oct 29 15:06 lp1p5-h0.pdf
-rw-r--r--    1 root root   42788 Oct 29 15:06 lp1p5.pdf
-rw-r--r--    1 root root  679904 Oct 29 15:06 lp20-h0.pdf
-rw-r--r--    1 root root  793914 Oct 29 15:06 lp20.pdf
```

So I think if we delete the redundant/incorrect files from a Linux machine this would fix it (not that they are of different sizes). @dennisguse, which ones are correct?

**Comment by simaocampos** [comment]
In the source folder for the manual files, before I uploaded it, I have:
7644

May 20 2013

LP10-h0.pdf

17930

May 20 2013

LP10.pdf

12880

May 20 2013

LP12-h0.pdf

14679

May 20 2013

LP12-h0new.pdf

13202

May 20 2013

LP12.pdf

8496

May 20 2013

LP12new.pdf

8829

May 20 2013

LP35-h0.pdf

22446

May 20 2013

LP35.pdf

7703

May 20 2013

LP7-h0.pdf

19999

May 20 2013

LP7.pdf

7857

May 20 2013

lp14-h0.pdf

23640

May 20 2013

lp14.pdf

9382

May 20 2013

lp1p5-h0.pdf

42788

May 20 2013

lp1p5.pdf

679904

May 20 2013

lp20-h0.pdf

793914

May 20 2013

lp20.pdf

**Comment by dennisguse** [comment]
@ludomal you are right. I added the files in upcase without seeing that existed in lowercase. I will revert the commit in the evening and change the figure include in the latex files. My fault.
