### ISSUE TITLE
Repository: Create STL2019 release

### ISSUE THREAD

**Issue by ludomal** [openitu/STL#127]
A package should be created and published. The package should contain:
- a copy of the source code as approved by SG12
- binaries for different platforms

**Comment by dennisguse** [comment]
Crafting a release on Github is simple: 
1. Select the branch (master) and thus the commit,
2. Prepare a ZIP file containing the code and the binaries,
3. Provide a proper description.

In addition, we need to update the _MANUAL.PDF_ within in the repository.

More details can be found here.
https://help.github.com/articles/creating-releases/

**Comment by dennisguse** [comment]
Two more minor issues.

_Changelogs_
In the code, there are some changelogs that are not up to date.
For example: https://github.com/openitu/STL/blob/dev/src/basop/README.md

Should we leave them as they are, remove them, or do we need to update these?

_Version code_
Almost all programs provide version information such as
https://github.com/openitu/STL/blob/dev/src/g711/g711demo.c#L182

Should we leave them as they are, remove them, or do we need to update these?

**Comment by ludomal** [comment]
@dennisguse, I think we are ready to proceed, once removed MANUAL.pdf.  
Shall we generate the release? I can generate the MacOS version.

**Comment by ludomal** [comment]
Closing this issue as STL2019 release was generated. 
Other topics within this thread may be discussed in a separate thread.
