### ISSUE TITLE
Drop unsup/pshar

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#14]
Program is not used, isn't it?

**Comment by dennisguse** [comment]
pshar is still making problems (at least on Debian).
@simaocampos  Can we drop it completely?

**Comment by dennisguse** [comment]
You are right. However, pshar does not provide useful functionality anymore. Therefore, I would like to remove it completely and thus reducing the maintenance effort. If somebody needs it, it is still available in STL2009. 
What do you think?

**Comment by ludomal** [comment]
I agree, let's remove it. As Simão commented above, this too is not longer needed.
I will merge the request.
