### ISSUE TITLE
STLmanual.pdf missing in G.191 (03/23)

### ISSUE THREAD

**Issue by MarkusMultrus** [openitu/STL#175]
This is not a real software issue, but I'm not sure how else to raise awareness to this: In the latest G.191 version (03/23), which can be downloaded from https://www.itu.int/rec/T-REC-G.191-202303-I/en, the STLmanual.pdf is missing. Unfortunately, this is an important piece of information...

In previous versions (e.g. [G.191 (07/22)](https://www.itu.int/rec/T-REC-G.191/recommendation.asp?lang=en&parent=T-REC-G.191-202207-S)) this file was still part of the zip-file, and even earlier it was even offered for a seperate download.

**Comment by malenov** [comment]
Hi @MarkusMultrus, the latest STL manual can be downladed [here ](https://github.com/openitu/STL/releases/download/v2023/STL2023-manual.pdf) but I'm guessing that you already know this and that it was not the point of your post. I also agree that it'd be good to have it available as an attachment at the official ITU website.

**Comment by ludomal** [comment]
Thank you, @MarkusMultrus, for raising this issue and @malenov for pointing Markus to the release section of this repository.

I agree that the manual should be accessible on the ITU website. I will try to get this resolved as soon as possible.

**Comment by maadolph** [comment]
Thank you, @MarkusMultrus, for raising the issue. The Zip-file on the ITU website has been replaced. It now includes the STL 2023 manual.

**Comment by simaocampos** [comment]
The problem has been solved at:
https://www.itu.int/rec/T-REC-G.191-202303-I/en

The zip file now includes the manual and is set for public download.

Best,
Simão

From: Markus Multrus ***@***.***>
Sent: Monday, 12 February, 2024 10:01
To: openitu/STL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openitu/STL] STLmanual.pdf missing in G.191 (03/23) (Issue #175)


This is not a real software issue, but I'm not sure how else to raise awareness to this: In the latest G.191 version (03/23), which can be downloaded from https://www.itu.int/rec/T-REC-G.191-202303-I/en, the STLmanual.pdf is missing. Unfortunately, this is an important piece of information...

In previous versions (e.g. G.191 (07/22)<https://www.itu.int/rec/T-REC-G.191/recommendation.asp?lang=en&parent=T-REC-G.191-202207-S>) this file was still part of the zip-file, and even earlier it was even offered for a seperate download.

-
