### ISSUE TITLE
Documentation: the source code for the manual

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#39]
The source file of the (stl2009man_LC.pdf) is not included.

The stl2009man_LC.pdf is included as MANUAL.PDF

**Comment by simaocampos** [comment]
The draft updated manual for the STL as of June 2014 has been uploaded under folder "manual". Sub-folder "archives" contains a copy of older versions of the library, albeit not for the 2009 version (editor: Claude Lamblin if I recall correctly).
