### ISSUE TITLE
spdemo: fails on MacOS using clang

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#46]
Executing spdemo results in "Abort trap: 6".

The issue seems to be a result of: 
`  FIND_PAR_S (9, "_Left of right adjusted? ..... ", just, just);`
https://github.com/dennisguse/stl2009/blob/master/src/utl/spdemo.c#L538

Something goes wrong in this macro.

Issue #42 is related.

**Comment by ludomal** [comment]
I have stumbled on the same issue while reviewing #107 and I have not realized that there was a bug report already created for this issue.

spdemo expects 9 parameters to be passed as command line and only 8 are passed in the regression tests, thus the error.

There are two sections in spdemo that parse the command line parameters and one of them (lines 530 to 538) looks outdated. 

This needs to be reviewed as I am not sure spdemo operates correctly as is. @simaocampos, do you have any insights?

**Comment by simaocampos** [comment]
Not on the top of my mind, would need to dig into the code and try to remember. I am afraid I will not be able to do that before the SG12 meeting :-(

**Comment by dennisguse** [comment]
I would furthermore like to replace the macros `GET_PAR_X` and `FIND_PAR_X` using regular functions.
Actually a simple task, but will be very helpful for debugging (and using macros here is not really beneficial anyhow).

**Comment by simaocampos** [comment]
This macro approach was really needed to support weak compilers. I would suggest to keep it.
Simão

**Comment by dennisguse** [comment]
@simaocampos what do you mean by weak compiler?

Would it be problematic to implement these as functions (even inline would be possible)?
I don't see why this might be problematic for newer compilers.

**Comment by simaocampos** [comment]
Some that had problems handling command line commands.
Simão

**Comment by ludomal** [comment]
Now solved with #116
