### ISSUE TITLE
fir: tests fail

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#49]
`firdemo` and `fir` tests fail for file verfication.
The verification tests fail as the computed files are slightly different than the reference files.

Used Ubuntu 16.10 (64bit).
Patch status today.

[LastTest.log.txt](https://github.com/dennisguse/stl2009/files/992226/LastTest.log.txt)

**Comment by othiman** [comment]
These test failed for me on three tested platforms (MacOS High Sierra, Windows 7 VS 2015, Linux Centos 7). Does anyone know which platform and compiler was used to produce the reference data?

**Comment by dennisguse** [comment]
Sadly no (at least not to my knowledge).
I just know that it ist _not_ an big vs. little endian issue.
If I remember correctly, it felt like a float precision issue... 

@simaocampos Can you provide further information?

**Comment by ludomal** [comment]
This is now fixed. The original test was using ```sub``` tool for comparing signals which allows equivalence for samples within +/- 1 of the original values. See #55.

**Comment by othiman** [comment]
With #74 and #83 this tests all pass for me on Ubuntu 18.04 (64 bit)

**Comment by dennisguse** [comment]
#74 and #83 are merged.

**Comment by simaocampos** [comment]
> ... Does anyone know which platform and compiler was used to produce the reference data?

Long story, started early 1990s. Evolved over time in various systems, at the beginning with MSDOS (16-bit; Turbo-C compiler) and SunOS (cc; with Motorola CPUs before the SPARC architecture); so both big and little endian. Portability ensured transitioning from different compilers and platforms with various flavors of Unix and then 32 bit platforms (eg Win32) till at least 2002. At that time, I stopped maintaining actively the STL. This is told in the manual, introduction chapter.
