### ISSUE TITLE
g728fixed: one test fails

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#54]
Test `g728fp-dec-post-verify` fails.

Files are slightly different.

Used Ubuntu 16.10 (64bit).
Patch status today.

[LastTest.log.txt](https://github.com/dennisguse/stl2009/files/992261/LastTest.log.txt)

**Comment by ludomal** [comment]
```g728fp``` was called with ```enc``` instead of ```dec``` in ```src/g728/g728fixed/CMakeLists.txt```.

**Comment by othiman** [comment]
With open PRs #77 this test pass for me on Ubuntu 18.04 (64 bit)
