### ISSUE TITLE
rpelt: tests fail

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#56]
Failing tests:
* rpeltdemo-ulaw2-verify
* rpeltdemo-ulaw3-verify
* rpeltdemo-ulaw3-e_d-verify

Used Ubuntu 16.10 (64bit).
Patch status today.

[LastTest.log.txt](https://github.com/dennisguse/stl2009/files/992278/LastTest.log.txt)

**Comment by othiman** [comment]
with #82 now all repelt tests pass for me with Ubuntu 18.04. (64bit)
