### ISSUE TITLE
utl: tests fail

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#60]
Failing tests:
* scaldemo1-verify
* spdemo8-2-verify
* spdemo10-1-verify
* spdemo13-verify
* spdemo13-1-verify
* spdemo12-1-verify

Used Ubuntu 16.10 (64bit).
Patch status today.

[LastTest.log.txt](https://github.com/dennisguse/stl2009/files/992299/LastTest.log.txt)

**Comment by ludomal** [comment]
Tests now pass.
