### ISSUE TITLE
Activate continuous integration on Github repository

### ISSUE THREAD

**Issue by dennisguse** [openitu/STL#71]
For easier maintenance, it would be very helpful to activate a continuous integration tool.
At the moment, Travis CI (supports only Linux and OSX) seems to be suited.

**Comment by othiman** [comment]
See #81 for a first version of a .travis.yml config file. To execute it a travis account and integration is necessary.

**Comment by dennisguse** [comment]
@ludomal @simaocampos 
Could you activate TravisCI for this organization?
It should only take 2min following this link: https://travis-ci.com/

I am reluctant to do, as TravisCI requests access to all my public and private repositories (the later are anyhow in the cloud, but I don't like sharing them with anybody).

**Comment by ludomal** [comment]
It should now be all set up. Let me know is there is anything more to do.
