### ISSUE TITLE
Merging pull requests

### ISSUE THREAD

**Issue by othiman** [openitu/STL#84]
Hi,

it would be nice if someone could start to merge the PRs. I cherry-picked all PR (despite #79 and parts of #78) to https://github.com/othiman/STL/tree/all-pr and this leaves just 27 failed tests open. :-) 

Here, for reference, the last lines of output from Travis (Ubuntu 18.04 64bit docker container) of https://github.com/othiman/STL/tree/all-pr:

97% tests passed, 27 tests failed out of 862
Total Test time (real) =  16.47 sec
The following tests FAILED:
	141 - g711demo2-verify (Failed)
	145 - g711demo4-verify (Failed)
	149 - g711demo6-verify (Failed)
	151 - g711iplc1-verify (Failed)
	155 - g711iplc3-verify (Failed)
	180 - encg722-1-verify (Failed)
	182 - decg722-1-verify (Failed)
	184 - decg722-2-verify (Failed)
	186 - decg722-3-verify (Failed)
	781 - sv56demo1-verify (Failed)
	783 - sv56demo2-verify (Failed)
	786 - truncate1-verify (Failed)
	788 - truncate2-verify (Failed)
	790 - truncate3-verify (Failed)
	792 - truncate4-verify (Failed)
	794 - truncate5-verify (Failed)
	823 - xdecode1 (Failed)
	824 - xdecode1-verify (Failed)
	825 - xencode1 (Failed)
	826 - xencode1-verify (Failed)
	827 - xencode2-verify (Failed)
	829 - scaldemo1-verify (Failed)
	850 - spdemo8-2-verify (Failed)
	852 - spdemo10-1-verify (Failed)
	858 - spdemo13-verify (Failed)
	859 - spdemo13-1-verify (Failed)
	861 - spdemo12-1-verify (Failed)
Errors while running CTest

**Comment by dennisguse** [comment]
I plan to do it in the next weekend. Okay? Except #79 - somebody else need to approve.

**Comment by othiman** [comment]
Sounds perfect. :-)

**Comment by othiman** [comment]
Down to 6 failed test, whereof 4 are OK to fail (see #90). So only xencode is left. ;-)

The following tests FAILED:
	826 - xencode1-verify (Failed)
	827 - xencode2-verify (Failed)
	850 - spdemo8-2-verify (Failed)
	852 - spdemo10-1-verify (Failed)
	860 - spdemo14-1-verify (Failed)
	863 - spdemo15-1-verify (Failed)
Errors while running CTest

**Comment by dennisguse** [comment]
We are (almost) done :)
