### ISSUE TITLE
Integrate 3GPP updates to STL2018

### ISSUE THREAD

**Issue by ludomal** [openitu/STL#85]

**Comment by dennisguse** [comment]
@ludomal 
How do we proceed?
Tests are now (almost) working, so we could start working on the 3GPP, or?

**Comment by ludomal** [comment]
@dennisguse, I started to prepare the pull requests last night, squashing the commits.
 I have been working on the integration for a while on that branch [basops_integration](https://github.com/ludomal/STL/tree/basops_integration/src/basop). There are quite a few commits and changes.

I would propose to submit three pull requests to break the review down:
- Code for the new baseops
- Code for the test framework
- Documentation

Does this sound good?

**Comment by dennisguse** [comment]
Sounds excellent. Do you want to integrate the code first and we then start fixing the documentation (code and manual)? And what is the actual deadline?

**Comment by ludomal** [comment]
Yes, ideally we should integrate the code first then deal with the documentation. I have submitted two PRs for the code and test framework (#105, #106). The test framework should integrate nicely with the CMake structure.

I would need to submit the Draft Recommendation as soon as we can, and no later than Nov 14. I should be able to get the text ready relatively quickly. We just need to settle on the format (#101). The submission will be as a Word Document in an ITU template. I do not think we will get this generated automatically, and I do not think it is needed. Whatever comes out from #101 will be copy-paste into the ITU template.

As for the LaTeX document, I think we can afford a bit more flexibility on the date, although I would prefer if we complete it by Nov 14 too.

**Comment by dennisguse** [comment]
The code looks ok (ignoring for the time being WMOPS).
About the Draft Recommendation, I also think this will have to be done manually.

I will start cleaning the Latex documents a little bit more on the upcoming weekend.
Then we are slightly better prepared here.

**Comment by dennisguse** [comment]
Code incl. tests is integrated.

**Next step:**
Update of the manul.

**Comment by ludomal** [comment]
Let's close this one. I will create new items for the update of manual.
